version: '3.1'
services:
  api-catalog:
    build: api-catalog/.
    container_name: api-catalog
    ports:
      - 6070:6070
    restart: always
    links:
      - api-catalog-db

  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306

  api-reservation:
    build: api-reservation/.
    container_name: api-reservation
    ports:
      - 8070:8070
    restart: always
    links:
      - api-reservation-db

  api-reservation-db:
    container_name: api-reservation-db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_reservation'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3311:3306
